#!/usr/bin/env python3
"""Convert a 22.05 kHz PCM WAV into a normalized 8-bit PCM header for ESP32 DAC."""

import argparse
import pathlib
import wave


TARGET_PEAK = 0.92  # Leave headroom for the M5GO speaker amplifier.
TARGET_SAMPLE_RATE = 11025


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("source", type=pathlib.Path)
    parser.add_argument("output", type=pathlib.Path)
    parser.add_argument("--symbol", default="construction_complete_pcm",
                        help="C++ array symbol to generate (default: %(default)s)")
    args = parser.parse_args()

    with wave.open(str(args.source), "rb") as wav:
        if wav.getnchannels() != 1 or wav.getsampwidth() != 2:
            raise ValueError("source must be 16-bit mono PCM WAV")
        if wav.getframerate() != TARGET_SAMPLE_RATE * 2:
            raise ValueError("source must use a 22,050 Hz sample rate")
        raw = wav.readframes(wav.getnframes())

    samples = [int.from_bytes(raw[i:i + 2], "little", signed=True)
               for i in range(0, len(raw), 2)]
    # GPIO25's direct DAC playback is stable at 11.025 kHz on the M5GO. Average
    # each pair to low-pass before halving the rate, avoiding the aliasing from
    # simply dropping every other sample.
    samples = [(samples[i] + samples[i + 1]) // 2
               for i in range(0, len(samples) - 1, 2)]
    peak = max((abs(sample) for sample in samples), default=1)
    scale = (32767 * TARGET_PEAK) / peak
    pcm = bytes(max(0, min(255, round((sample * scale) / 256 + 128)))
                for sample in samples)

    lines = [
        "// Generated by tools/convert_completion_sound.py; do not edit manually.",
        "// Unsigned 8-bit mono PCM, 11,025 Hz, pair-averaged and normalized to 92%.",
        f"const uint8_t {args.symbol}[] = {{",
    ]
    for offset in range(0, len(pcm), 16):
        lines.append("  " + ", ".join(f"0x{sample:02X}" for sample in pcm[offset:offset + 16]) + ",")
    lines.extend(["};", f"const size_t {args.symbol}_len = {len(pcm)};", ""])
    args.output.write_text("\n".join(lines))
    print(f"Wrote {args.output} ({len(pcm)} samples at {TARGET_SAMPLE_RATE} Hz; scale {scale:.3f})")


if __name__ == "__main__":
    main()
